# Generated by Django 5.2.10 on 2026-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(upload_to='chais/'),
        ),
    ]
