# Generated by Django 5.2.10 on 2026-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_description_alter_chaivariety_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
